export { default as header } from './header.png'
export { default as classroomBG } from './classroomBG.png'
export { default as yellowBar } from './yellowBar.png'
export { default as purpleButton } from './purplebutton.svg'
export { default as bossHealth } from './bossHealth.png'
export { default as bossFightBG } from './bossFightBG.png'
export { default as rocket } from './rocket.png'
export { default as logoBlack } from './logoBlack.svg'
